---
- name: create Airflow user account
  user:
    name: airflow
    comment: Airflow service user
    shell: /bin/bash

- name: Create Airflow config folder
  file:
    path: "{{ item }}"
    state: directory
    owner: airflow
    group: airflow
    mode: 0775
  loop:
    - "{{ apache_airflow_home }}"
    - "{{ apache_airflow_run }}"
    - "{{ apache_airflow_dags_folder }}"

- name: Install Dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - python3-dev
    - gcc
    - build-essential
    - libssl-dev 
    - libmysqlclient-dev
    - python3.7

# - name: Set python 3.7 as default
#   #command: sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2
#   alternatives:
#     name: python3
#     link: /usr/bin/python3
#     path: /usr/bin/python3.7

- name: Install Airflow packages
  pip:
    executable: pip3
    name: "{{ item }}"
  loop:
    - apache-airflow
    - apache-airflow[mysql]
    - mysqlclient
    - mysql-connector

- name: Set airflow home
  lineinfile:
    path: /etc/environment
    line: 'AIRFLOW_HOME={{ apache_airflow_home }}'

- name: Copy the airflow env file
  template:
    src: airflow.j2
    dest: /etc/systemd/airflow
  notify: restart airflow

- name: Copy the airflow configuration file to airflow home
  template:
    src: airflow.cfg.j2
    dest: "{{ apache_airflow_home }}/airflow.cfg"
    owner: airflow
    group: airflow
  notify: restart airflow
  
- name: Initializing DB
  command: "{{ apache_airflow_execuitable }} initdb"
  environment:
    AIRFLOW_HOME: "{{ apache_airflow_home }}"
  become_user: airflow
  become: true

- name: Move systemd service files
  template:
    src: "{{ item }}.service.j2"
    dest: /etc/systemd/system/{{ item }}.service
  notify: reload systemd
  loop:
    - airflow-scheduler
    - airflow-webserver
