---

- name: reload systemd
  systemd:
    daemon_reload: yes
  
- name: restart airflow
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - airflow-webserver
    - airflow-scheduler